### ISSUE TITLE
Why empty body for login?

### ISSUE THREAD

**Issue by cho-is** [James1345/django-rest-knox#13]
Is there any particular reason of why POST empty body approach for login?

An perhaps a stupid question is: how do you do that? I always get Authentication credentials were not provided.

**Comment by tr00st** [comment]
The empty body for the LoginView is so that another auth method is used when obtaining the token - knox intends for another auth class to be used (eg: BasicAuthentication) for the request to provide an initial authentication, and then use the generated token for the rest of the session. This means that one can plug in any authentication method as applicable (eg: OAuth, Digest, or some custom method).

An empty body is the most auth-method-agnostic way of dealing with that, AFAIK :smile: 

...but correct me if I'm wrong, @James1345

**Comment by James1345** [comment]
@tr00st is correct

**Comment by cho-is** [comment]
Thank you very much for you prompt answers.

I am trying to use `django-rest-auth` in combination with `django-rest-knox`

So I am going to have a deeper look and see what I can do.

**Comment by pylixm** [comment]
@cho-is , can you tell me how to get the token ? I got this error .
`"detail": "You do not have permission to perform this action."`

This is my cmd :
```curl -H 'Content-Type: application/json' -u admin:LIxm561 -X POST  http://localhost:8000/api/auth/login/```

url.py :
```python
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', admin.site.urls),
    #url(r'^', include('apis.urls')),
    url(r'api/auth/', include('knox.urls')),

]
```
settings.py 
```python

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        #'rest_framework.authentication.TokenAuthentication',
        #'rest_framework.authentication.BasicAuthentication',

    ]
}
```

`

**Comment by tr00st** [comment]
@pylixm, looks like the problem is that you've disabled the BasicAuthentication class, and are then attempting to use basic authentication - you'll need to uncomment the BasicAuthentication line in the DEFAULT_AUTHENTICATION_CLASSES entry.

Make sure to then add knox.auth.TokenAuthentication to the list so you can use both. Your settings should look something like:

```
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'knox.auth.TokenAuthentication',

    ]
}
```

**Comment by pylixm** [comment]
It work ! @tr00st  Thank you very much . I need to supplement more knowledge. :smile:

**Comment by jyr** [comment]
Hi,

I have the same issue, my config is:

urls.py
```
urlpatterns = [
    url(r'api/auth/', include('knox.urls')),
]
```

settings.py
```
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'knox.auth.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated', )
}
```

Logs
```
api_1        | Unauthorized: /api/auth/login/
api_1        | [05/Sep/2019 21:44:09] "POST /api/auth/login/ HTTP/1.1" 401 58
```

Thanks
