### ISSUE TITLE
Authentication doesn't create a sessionid

### ISSUE THREAD

**Issue by denny64** [James1345/django-rest-knox#54]
I'm trying out this project: https://github.com/Seedstars/django-react-redux-base which is using Knox and when I login via the frontend, django doesn't create a sessionId, although the login was successful. Attempting to access the django admin dashboard will ask you to login again, even though my user is a super user. Is this something to do with the way Knox has been set up?

**Comment by belugame** [comment]
Token-based authentication is state-less and has no persisting session on the server, so that is why there is no session for your frontend login.

The django-built-in admin uses a Session and is entirely independent from knox, which is a plugin for django. django's admin will not look for or use any knox token that is set on the request. That is why you need to login separately

Hope that clears up your questions :).

**Comment by denny64** [comment]
Thanks for your answer. That makes sense now! Do you know how i can get django to create a session during the login process? What can I use?

**Comment by denny64** [comment]
The main issue that i am experiencing is that when i do a GET request, I can't access request.user via self.context in the serializer, is there another way to get the user?

**Comment by belugame** [comment]
First you need to confirm that your user is indeed authenticated, please do so in the view. That is how far your rest-knox config affects the situation.

Because a serializer class does not usually have access to the request object and rest-knox has nothing to do with the context that is passed to a serializer.
